services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: llm-zoomcamp-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped



  pgvector:
    image: pgvector/pgvector:pg17
    container_name: llm-zoomcamp-pgvector
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=pswd
    - POSTGRES_DB=faq
    ports:
    - "5432:5432"
    volumes:
    - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  esdata:
  pgvector_data: